In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,32,7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
myarr.shape
myarr[0]

3

In [5]:
myarr.shape

(4,)

In [6]:
myarr[1]=35

In [7]:
myarr

array([ 3, 35, 32,  7])

# Array creation: conversion from other python structures

In [8]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
zeroes=np.zeros((2,5))

In [13]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
rng=np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
lspace=np.linspace(1,50,9)

In [17]:
lspace

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

In [18]:
# to generate an array of given size with random variables

In [19]:
emp=np.empty((4,6))

In [20]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        8.45605478e-307, 7.56587585e-307, 7.56593017e-307],
       [1.24610383e-306, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22522597e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.37962185e-306,
        1.37962049e-306, 1.24610723e-306, 1.69121367e-306]])

In [21]:
# to make an same array

In [22]:
emp_like=np.empty_like(lspace)

In [23]:
emp_like

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

In [24]:
# creating a identity matrix of given size

In [25]:
ide=np.identity(3)

In [26]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
ide.shape

(3, 3)

# Reshaping the array

In [28]:
arr=np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.reshape(11,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.shape

(99,)

In [33]:
arr=arr.reshape(11,9)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
# axis0: top to bottom  and axis1: left to right

In [37]:
x=[[1,2,3],[5,6,7],[3,4,5]]

In [38]:
x1=np.array(x)

In [39]:
x1

array([[1, 2, 3],
       [5, 6, 7],
       [3, 4, 5]])

In [40]:
x1.sum(axis=0)

array([ 9, 12, 15])

In [41]:
x1.sum(axis=1)

array([ 6, 18, 12])

In [42]:
x1.T

array([[1, 5, 3],
       [2, 6, 4],
       [3, 7, 5]])

In [43]:
for items in x1.flat:
    print(items)

1
2
3
5
6
7
3
4
5


In [44]:
x1.ndim

2

# ARG FUNCTIONS

In [45]:
one =np.array([1,2,4,90,5,6])

In [46]:
one.argmax() #position of max element

3

In [47]:
one.argmin()

0

In [48]:
one.argsort()

array([0, 1, 2, 4, 5, 3], dtype=int64)

In [49]:
# arg function in 2d matrix

In [50]:
m1=np.arange(40)

In [51]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [52]:
m2=m1.reshape(4,10)

In [53]:
m2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [54]:
m2.argmin()

0

In [55]:
m2.argmax()

39

In [56]:
m2.argsort()

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int64)

In [57]:
m2.argsort(axis=0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]], dtype=int64)

In [58]:
m2.argsort(axis=1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int64)

# mathematical operations in array

In [59]:
arr=np.arange(9)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
x=arr.reshape(3,3)

In [62]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
x2=np.array([[0, 3, 6],
       [3, 4, 5],
       [3, 4, 6]])

In [64]:
x+x2

array([[ 0,  4,  8],
       [ 6,  8, 10],
       [ 9, 11, 14]])

In [65]:
x*x2 #this is not the multiplication of 2 matrix

array([[ 0,  3, 12],
       [ 9, 16, 25],
       [18, 28, 48]])

In [66]:
np.where(x>5)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [67]:
np.count_nonzero(x)

8

x = np.arange(10)
x
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

x[:5]
array([0, 1, 2, 3, 4])

x[4:]
array([4, 5, 6, 7, 8, 9])

x[4:7]
array([4, 5, 6])


x[ : : 2]
array([0, 2, 4, 6, 8])


x[1::2]
array([1, 3, 5, 7, 9])


x[::-1]
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [68]:
u=np.array([1,3,4,5])

In [69]:
np.count_nonzero(u)

4

In [70]:
np.size(u)

4

In [71]:
list(range(9,16,2))

[9, 11, 13, 15]

In [72]:
np.random.rand(1,10)

array([[0.50940021, 0.60615002, 0.90560581, 0.45143269, 0.98926633,
        0.68890436, 0.87793398, 0.34829387, 0.96984628, 0.53382363]])