In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([1, 0, np.nan, np.inf])

In [3]:
p=np.isfinite(a)

In [4]:
p

array([ True,  True, False, False])

In [6]:
np.where(p==True)

(array([0, 1], dtype=int64),)

In [9]:
np.isnan(a)

array([False, False,  True, False])

In [10]:
np.isinf(a)

array([False, False, False,  True])

In [14]:
x=np.arange(30,71)

In [15]:
x

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])