In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.8.0'

In [3]:
a=tf.constant(10)

In [4]:
b=tf.constant(20)

In [5]:
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [6]:
tf.executing_eagerly()

True

In [7]:
c=a+b

In [8]:
c.numpy()

30

In [9]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# hide warnings
#import warnings 
#warnings.filterwarning ('ignore')


In [10]:
a_matrix = tf.constant([[1,2],[3,4]])
b_matrix = tf.constant([[5,6],[7,8]])

In [11]:
b_matrix.numpy()

array([[5, 6],
       [7, 8]])

In [12]:
tf.matmul(a_matrix,b_matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [13]:
print(a_matrix.numpy(),b_matrix.numpy(),sep="\n")

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [14]:
d=tf.Variable(np.random.randn(3,3))

In [15]:
d

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float64, numpy=
array([[-1.69872575, -0.84833013,  1.26521534],
       [-1.88833056,  1.81507664, -0.54044007],
       [ 0.11849518, -1.35715274, -1.38124258]])>

In [16]:
from datetime import datetime
import os
import pathlib

t = datetime.utcnow().strftime("%Y%m%d%H%M%S") 
log_dir = "tf_logs"
logd = "/tmp/{}/r{}/".format(log_dir, t)

# Then every time you have specified a graph run:
# file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

# Make directory if it doesn't exist

from pathlib import Path
home = str(Path.home())

logdir = os.path.join(os.sep,home,logd)

if not os.path.exists(logdir):
    os.makedirs(logdir)

# LOOK AT THE COMPUTATIONAL GRAPH WITH @tf.function

In [17]:
# tf.function is a very useful module that caln be used to convert simple python function into a hinh computational graph that can be run on any runtime environment.
#when we build a model and then traun and compile the model and optimize the execution

In [18]:
@tf.function
def func(a,b):
    with tf.name_scope('first'):
        z=tf.multiply(a,b,name='z')
    with tf.name_scope('second'):
        y1=tf.constant(3,name='3')
        y2=tf.constant(4)
        w1=tf.add(z,y1,name='w1')
        w2=tf.add(z,y2,name='w2')
    return (w1+w2)    
        

In [19]:
writer=tf.summary.create_file_writer(logdir)
tf.summary.trace_on()

In [20]:
a=tf.constant(3)
b=tf.constant(4)
func(a,b)
with writer.as_default():
    tf.summary.trace_export(
        name='func',
        step=0,
        profiler_outdir=logdir
    )
    

In [21]:
logdir

'C:/tmp/tf_logs/r20220314120832/'

# calculating gradients

In [22]:
w=tf.Variable(3.0)

# gradiant scope for the function w^2
with tf.GradientTape() as tape:
    expression =tf.exp(w)+2*w+w*w
grad=tape.gradient(expression,w)  
print(f'the gradient of exp at {w.numpy()} id {grad.numpy()}')

the gradient of exp at 3.0 id 28.08553695678711


In [23]:
# calculating gradient of the simoid function

In [24]:
def sigmoid(x):
    return 1/(1+tf.exp(-x))

In [25]:
x=tf.Variable(0.)
with tf.GradientTape() as tape:
    sig=sigmoid(x)
res=tape.gradient(sig,x).numpy()
print('The gradient of the sigmoid function at 0.0 is ',res)

The gradient of the sigmoid function at 0.0 is  0.25


In [26]:
a=tf.constant(1)
b=tf.constant(10)
c=tf.add(a,b)
c

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [27]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x = tf.constant(35, name='x')
y = tf.Variable(x + 5, name='y')
z = tf.Variable(4)
a = y + z
with tf.Session() as session:
        print("x = ", session.run(x)) 

Instructions for updating:
non-resource variables are not supported in the long term
x =  35


In [28]:
sess=tf.Session()
f = tf.Variable(99, name = 'f')
sess.run(f.initializer) # !!! error if we don't
sess.run(f)

99

# Global variable initialization

In [29]:
x = tf.constant(35, name='x')
y = tf.Variable(x + 5, name='y')
#model = tf.global_variables_initializer() # variables ke liye isse use karnaa hai
with tf.Session() as session:
        print("x = ", session.run(x)) 
 #       session.run(model)
        print("y = ", session.run(y))

x =  35


FailedPreconditionError: Graph execution error:

Attempting to use uninitialized value y_1
	 [[{{node _retval_y_1_0_0}}]]

# more with graphs

In [30]:
graph3 = tf.Graph()

with graph3.as_default():

    with tf.name_scope('const_add1') as scope:
        x = tf.constant(2, name='x')
        y = tf.constant(3, name='y')
        z = tf.multiply(x,y, name='z')
    with tf.name_scope('second') as scope:
        w1 = tf.add(z, 3, name='w1')
        w2 = z - 4
    sess3 = tf.Session(graph=graph3)
    print(sess3.run(w1))
    print(sess3.run(w2))

9
2


In [31]:
%load_ext tensorboard

In [32]:
logdir

'C:/tmp/tf_logs/r20220314120832/'